
name: Main Workflow

on:
  workflow_dispatch:
  #workflow_call:
    inputs:
      envIdentifier:
        description: 'Environment Identifier'
        required: true
        type: string

jobs:
  # This job reads parameters from EnvInfo.txt and sets them as outputs.
  # These outputs are then used in the Playwright tests workflow.
  read-params:
    runs-on: self-hosted
    env:
      ENV_IDENTIFIER: ${{ github.event.inputs.envIdentifier }}
      #ENV_IDENTIFIER: ${{ inputs.envIdentifier }}
    # Outputs are set to be used in the next job.
    outputs:
      urlUserPortal: ${{ steps.set-env.outputs.urlUserPortal }}
      usernameUserPortal: ${{ steps.set-env.outputs.usernameUserPortal }}
      passwordUserPortal: ${{ steps.set-env.outputs.passwordUserPortal }}
      urlAdminPortal: ${{ steps.set-env.outputs.urlAdminPortal }}
      usernameAdminPortal: ${{ steps.set-env.outputs.usernameAdminPortal }}
      passwordAdminPortal: ${{ steps.set-env.outputs.passwordAdminPortal }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read parameters from EnvInfo.txt and set outputs
        id: set-env
        shell: pwsh
        run: |
          $filePath = Join-Path $env:GITHUB_WORKSPACE "apps/xd-e2e/utils/EnvInfo.txt"
          Write-Host "Reading EnvInfo.txt file from path: $filePath"
          if (-Not (Test-Path $filePath)) {
            Write-Error "EnvInfo.txt file not found at path: $filePath"
            exit 1
          }
          
          $envIdentifier = $env:ENV_IDENTIFIER # Get the environment identifier from the input
          Write-Host "Using environment identifier: $envIdentifier"
          $lines = Get-Content $filePath

          foreach ($line in $lines) {
            if ($line -match "^\s*([^#][^=]*)=(.*)$") {
              $key = $matches[1].Trim()
              $value = $matches[2].Trim()

              if ($key -eq ("${envIdentifier}_USER_PORTAL_URL").ToUpper()) {
                echo "urlUserPortal=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              } elseif ($key -eq ("${envIdentifier}_USER_PORTAL_USERNAME").ToUpper()) {
                echo "usernameUserPortal=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              } elseif ($key -eq ("${envIdentifier}_USER_PORTAL_PASSWORD").ToUpper()) {
                echo "passwordUserPortal=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              } elseif ($key -eq ("${envIdentifier}_ADMIN_PORTAL_URL").ToUpper()) {
                echo "urlAdminPortal=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              } elseif ($key -eq ("${envIdentifier}_ADMIN_PORTAL_USERNAME").ToUpper()) {
                echo "usernameAdminPortal=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              } elseif ($key -eq ("${envIdentifier}_ADMIN_PORTAL_PASSWORD").ToUpper()) {
                echo "passwordAdminPortal=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              }
            }
          }
  # This job calls the Playwright tests workflow and passes the parameters read from EnvInfo.txt.
  # The Playwright workflow will use these parameters to run tests.
  call-playwright-yml-file:
    needs: read-params
    uses: ./.github/workflows/playwright.yml
    with:
      urlUserPortal: ${{ needs.read-params.outputs.urlUserPortal }}
      usernameUserPortal: ${{ needs.read-params.outputs.usernameUserPortal }}
      passwordUserPortal: ${{ needs.read-params.outputs.passwordUserPortal }}
      urlAdminPortal: ${{ needs.read-params.outputs.urlAdminPortal }}
      usernameAdminPortal: ${{ needs.read-params.outputs.usernameAdminPortal }}
      passwordAdminPortal: ${{ needs.read-params.outputs.passwordAdminPortal }}

  # This job provides the status of Playwright tests once execution is completed.
  print-status:
    runs-on: self-hosted
    needs: call-playwright-yml-file
    if: always() # Ensure this job runs even if the previous one fails
    steps:
      - name: Print Playwright status
        run: |
          $status = "${{needs.call-playwright-yml-file.outputs.playwright-status}}"
          Write-Output "Playwright tests status: $status"

